Fix for github html doc uploader workflow (#3601)
Upgrade python to 3.12

The workflow has been failing since PR#3543 was merged, as the new
dependencies require python >=3.10.

Failing job:
https://github.com/redhat-best-practices-for-k8s/certsuite/actions/runs/24036088552/job/70095942859#step:3:161
```
ERROR: Ignored the following versions that require a different python
version: 2.33.0 Requires-Python >=3.10; 2.33.1 Requires-Python >=3.10;
2026.2.19 Requires-Python >=3.10; 2026.2.28 Requires-Python >=3.10;
2026.3.32 Requires-Python >=3.10; 2026.4.4 Requires-Python >=3.10;
3.10 Requires-Python >=3.10; 3.10.1 Requires-Python >=3.10;
3.10.2 Requires-Python >=3.10; 4.5.0 Requires-Python >=3.10;
4.5.1 Requires-Python >=3.10; 4.6.0 Requires-Python
>=3.10; 4.7.0 Requires-Python >=3.10; 4.7.1
Requires-Python >=3.10; 4.8.0 Requires-Python >=3.10; 4.9.0
Requires-Python >=3.10; 4.9.1 Requires-Python >=3.10; 4.9.2
Requires-Python >=3.10; 4.9.4 Requires-Python >=3.10; 8.2.0
Requires-Python >=3.10; 8.2.1 Requires-Python >=3.10; 8.2.2
Requires-Python >=3.10; 8.3.0 Requires-Python >=3.10; 8.3.1
Requires-Python >=3.10; 8.3.2 Requires-Python >=3.10; 8.8.0
Requires-Python >=3.10; 8.9.0 Requires-Python >=3.10; 9.0.0
Requires-Python >=3.10
```
Also added manual trigger for doc publich workflow.

Signed-off-by: Gonzalo Reyero Ferreras <greyerof@redhat.com>